version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    environment:
      - APP_ENV=${APP_ENV:-development}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    ports:
      - "8900:8900"
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - APP_ENV=${APP_ENV:-production}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    depends_on:
      - rabbitmq
